#Scene
image cuarto_Honoka = "images/Cuarto_Honoka.png"
image otonoki = "images/Otonokizaka.png"
image otonoki2 = "images/otonoki2.png"
image otonoki4 = "images/otonoki4.png"
image atardecer = "images/Atardecer.png"
image cielo = "images/cielo.png"
image pasillo = "images/Pasillo.jpg"
image aula = "images/Aula.png"
image arise1 = "images/Elements/Arise1.jpg"
image basic = "images/Elements/basic.png"
image festival = "images/Elements/festival.png"
image insatisfaccion = "images/Elements/scary.png"

#Sprites
image HonokaPan = "images/personajes/Honokapan.png"
image KousakaHonoka = "images/personajes/HonokaBase.png"
image UmiS = "images/personajes/UmiSonoda.png"
image KotoriM = "images/personajes/KotoriMinami.png"

#Elements
image beginner = "images/Elements/begin1.png"
image beginner2 = "images/Elements/begin2.png"
image HonokaSad = "images/Elements/HonokaSad.png"
image HonokaCry = "images/Elements/HonokaCry.png"
image determinacion = "images/Elements/determinacion.png"
image photo = "images/Elements/photo.png"
image capitulo1 = "images/Capitulos/TCapitulo1.png"
image capitulo2 = "images/Capitulos/TCapitulo2.png"
image cKotori = "images/Comentarios/Kotori.png"
image MenuElec = "images/MenuElec.png"
