define audio.Main1 = "audio/Main.mp3"
define audio.Faito = "audio/faitodayo.mp3"
define audio.Otonoki = "audio/Otonoki.mp3"
define audio.PasilloMain = "audio/Pasillo.mp3"
define audio.Motivation = "audio/motivational.mp3"